# Path related
dataset_dir: data/raw/
dataset_path: covid_data.csv
dataset_cleaned_path: data/processed/covid_dataset.pkl
raw_dataset_path: data/processed/raw_dataset.pkl
cleaned_raw_dataset_path: data/processed/raw_dataset.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_set_rus_path:
- data/processed/x_rus.pkl
- data/processed/y_rus.pkl
train_set_ros_path:
- data/processed/x_ros.pkl
- data/processed/y_ros.pkl
train_set_sm_path:
- data/processed/x_sm.pkl
- data/processed/y_sm.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl
production_model_path: models/production_model.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# Columns by data type related:
object_columns:
- DATE_DIED
int_columns:
- USMER
- MEDICAL_UNIT
- SEX
- PATIENT_TYPE
- INTUBED
- PNEUMONIA
- AGE
- PREGNANT
- DIABETES
- COPD
- ASTHMA
- INMSUPR
- HIPERTENSION
- OTHER_DISEASE
- CARDIOVASCULAR
- OBESITY
- RENAL_CHRONIC
- TOBACCO
- CLASIFFICATION_FINAL
- ICU

# Predictors and label related
label: DATE_DIED
predictors:
- USMER
- MEDICAL_UNIT
- PATIENT_TYPE
- INTUBED
- PNEUMONIA
- AGE
- PREGNANT
- DIABETES
- COPD
- ASTHMA
- INMSUPR
- HIPERTENSION
- OTHER_DISEASE
- CARDIOVASCULAR
- OBESITY
- RENAL_CHRONIC
- TOBACCO
- CLASIFFICATION_FINAL
- ICU
- AGE_BIN

# Range of data related
range_boolean:
- 1
- 2
range_usmr:
- 1
- 99
range_medical_unit:
- 1
- 13
range_sex:
- 1
- 99
range_patient_type:
- 1
- 99
range_intubed:
- 1
- 99
range_pneumonia:
- 1
- 99
range_age:
- 0
- 121
range_age_bin:
- 0
- 8
range_pregnant:
- 1
- 99
range_diabetes:
- 1
- 99
range_copd:
- 1
- 99
range_asthma:
- 1
- 99
range_inmsupr:
- 1
- 99
range_hipertension:
- 1
- 99
range_other_disease:
- 1
- 99
range_cardiovascular:
- 1
- 99
range_obesity:
- 1
- 99
range_renal_chronic:
- 1
- 99
range_tobacco:
- 1
- 99
range_classification:
- 1
- 7
range_icu:
- 1
- 99
